create table collaborator (id int8 generated by default as identity, cpf varchar(255), name varchar(255), primary key (id));
create table item (id int8 generated by default as identity, description varchar(255), id_collaborator int8, primary key (id));
alter table if exists item add constraint FKmy4a0phro97tt751hifcwrvrq foreign key (id_collaborator) references collaborator;
create table collaborator (id int8 generated by default as identity, cpf varchar(255), name varchar(255), primary key (id));
create table item (id int8 generated by default as identity, description varchar(255), id_collaborator int8, primary key (id));
alter table if exists item add constraint FKmy4a0phro97tt751hifcwrvrq foreign key (id_collaborator) references collaborator;
